### ISSUE TITLE
Latest tag stuck at 2.19.0 for me

### ISSUE THREAD

**Issue by bonelifer** [ngxson/portainer-ce-without-annoying#9]
Latest tag stuck at 2.19.0 for me,changing docker compose file to point directly at 2.19.1 works though.

**Comment by Leolele99** [comment]
This seems to be the case, I can confirm!

**Comment by ngxson** [comment]
I'm not sure what's the root cause of this problem.

For now, I re-deploy manually latest tag. It should be 2.19.1

I suspect that because my CI job runs at 00:00, and maybe portainer also deploy the same moment on their side, there's a conflict. For now, I will run the CI job at 01:20 and we'll see if it fixes the problem.

**Comment by bonelifer** [comment]
Thanks. Updated and works.

**Comment by notjosh** [comment]
Adding this as a note/FYI in case someone has confusion about this like I did and stumbles on it via Google: as of 2.20.x, Portainer uses `latest` for LTS releases, and `sts` is the _actual_ latest version. See https://github.com/ngxson/portainer-ce-without-annoying/issues/13 for more detail.
